export const VIEW_TRANSITION_IOS_DURATION = 400;
export const VIEW_TRANSITION_ANDROID_DURATION = 200;
export const VIEW_TRANSITION_ANDROID_TOP = -20;
export const VIEW_TRANSITION_ANDROID_LEFT = -10;
